### ISSUE TITLE
Ignore unknown JSON keys

### ISSUE THREAD

**Issue by kernitus** [NyCodeGHG/retrofit2-kotlinx-serialization-converter#2]
Hello,

Thank you for keeping this library updated. I've been scratching my head for a while about this, I'm trying to get this serialiser factory to ignore any unknown keys, so as to not have to include loads of keys that I do not need. The [Kotlin serialisation docs](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#ignoring-unknown-keys) say that it can be accomplished with the `ignoreUnknownKeys` property, but it doesn't look like this library uses the Json builder at all. Is it possible to set this option in some way?

**Comment by NyCodeGHG** [comment]
This library actually uses the Json Builder more or less.
You can create a Json object with the builder and call asConverterFactory on that json object.
```kotlin
val contentType = "application/json".toMediaType()
val retrofit = Retrofit.Builder()
  .baseUrl("https://example.com/")
  .addConverterFactory(Json {
    ignoreUnkownKeys = true
  }.asConverterFactory(contentType))
  .build()
```

**Comment by kernitus** [comment]
Ah, that makes sense now. Thank you!
